source "https://rubygems.org"

ruby File.read(File.join(__dir__, '.ruby-version')).strip

gem "fastlane"
gem "xcode-install"
gem 'cocoapods', '~> 1.11', '>= 1.11.3'
gem 'cocoapods-core', :git => 'https://github.com/CocoaPods/Core.git'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
